### ISSUE TITLE
Unnecessary focus call

### ISSUE THREAD

**Issue by narkq** [cryptounicorns/desktop#4]
https://github.com/cryptounicorns/desktop/blob/b54d3896e2fd87cfc1bfbd67d83d31136d11b4b5/src/app/main.cljs#L39-L43

https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winshow
> win.show()
>
> Shows and gives focus to the window.

**Comment by olegakbarov** [comment]
Valid point, sir
